name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        generator:
          - Ninja
          - Xcode
        configuration: [Debug, Release]
        include:
          - generator: Ninja
            platform: Linux
            os: ubuntu-26.04
          - generator: Xcode
            platform: macOS
            os: macos-latest

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl3-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update
          brew install sdl3
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'libsidplayfp/libresidfp'
          regex: true
          file: "libresidfp-.*\\.tar\\.gz"
          target: 'subdir/'
      - name: build-lib
        run: |
          cd subdir
          tar -xf libresidfp*.tar.gz
          cd libresidfp*/.
          ./configure --disable-dependency-tracking
          make && sudo make install
      - uses: actions/checkout@v6
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G ${{ matrix.generator }} ..
          cmake --build .
