name: Build for Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          zip
          base-devel
        pacboy: >-
          toolchain:p
          cmake:p
          sdl3:p
          libresidfp:p
    - uses: actions/checkout@v7
      with:
        ref: ${{ github.ref }}
    - name: Get the tag name
      id: get_tag_name
      run: echo "tagname=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: build
      run: |
        mkdir build
        cd build
        cmake -G 'MSYS Makefiles' \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_STATIC=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" \
            ..
        cmake --build .
        cp ../readme.* ../README.* ../AUTHORS ../COPYING ../docs/goat_tracker_commands.pdf .
        zip loadtracker-${{ steps.get_tag_name.outputs.tagname }}.zip *.exe readme.* README.md AUTHORS COPYING goat_tracker_commands.pdf
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/loadtracker-${{ steps.get_tag_name.outputs.tagname }}.zip
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
